# This file contains the fastlane.tools configuration

update_fastlane # fastlane automatically update itself

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
   lane :beta do
     register_devices(devices_file: "./Match/devices.txt") # Sync test devices from file to itunesconnect
     match(force_for_new_devices: true) # Creates all required certificates & provisioning profiles
     ensure_git_status_clean # Ensure that your git status is not dirty
     increment_build_number xcodeproj: "ownCloud.xcodeproj" # Automatically increase the build number
     commit_version_bump(xcodeproj: "ownCloud.xcodeproj") # Commit the version bump
     push_to_git_remote # Push the new commit and tag back to git remote
     build_app(scheme: "ownCloud") # Build scheme
     changelog_from_git_commits # Generate the changelog based on last commits
     upload_to_testflight # Upload build to itunesconnnect
  end
end
