//
//  OCSavedSearch.h
//  ownCloudApp
//
//  Created by Felix Schwarz on 13.09.22.
//  Copyright © 2022 ownCloud GmbH. All rights reserved.
//

/*
 * Copyright (C) 2022, ownCloud GmbH.
 *
 * This code is covered by the GNU Public License Version 3.
 *
 * For distribution utilizing Apple mechanisms please see https://owncloud.org/contribute/iOS-license-exception/
 * You should have received a copy of this license along with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.en.html>.
 *
 */

#import <Foundation/Foundation.h>
#import <ownCloudSDK/ownCloudSDK.h>

typedef NSString* OCSavedSearchScope NS_TYPED_ENUM;
typedef NSString* OCSavedSearchUUID;
typedef NSString* OCSavedSearchUserInfoKey NS_TYPED_ENUM;

NS_ASSUME_NONNULL_BEGIN

@interface OCSavedSearch : NSObject <NSSecureCoding, OCDataItem, OCDataItemVersioning>

@property(strong) OCSavedSearchUUID uuid; //!< Unique ID of the saved search

@property(strong) OCSavedSearchScope scope; //!< The scope of the saved search

@property(assign) BOOL isTemplate; //!< This is a search template. Search templates can be restored right inside search. They restore search terms, scope but drop the location. This allows building reusable filters.

@property(strong,nullable) OCLocation *location; //!< The location for saved searches with folder or drive scope
@property(strong,nonatomic) NSString *name; //!< User-chosen or autogenerated name of the saved search. Falls back to .searchTerm if none was provided.
@property(readonly,nonatomic) BOOL isNameUserDefined; //!< User defined the name
@property(strong) NSString *searchTerm; //!< Search term parseable by OCQueryCondition+SearchSegmenter

@property(strong,nullable) NSDictionary<OCSavedSearchUserInfoKey, id> *userInfo; //!< Userinfo for richer UI presentation, only use types from OCEvent.safeClasses!

- (instancetype)initWithScope:(OCSavedSearchScope)scope location:(nullable OCLocation *)location name:(nullable NSString *)name isTemplate:(BOOL)isTemplate searchTerm:(NSString *)searchTerm userInfo:(nullable NSDictionary<OCSavedSearchUserInfoKey, id> *)userInfo;

@end

extern OCSavedSearchScope OCSavedSearchScopeFolder;
extern OCSavedSearchScope OCSavedSearchScopeContainer;
extern OCSavedSearchScope OCSavedSearchScopeDrive;
extern OCSavedSearchScope OCSavedSearchScopeAccount;

NS_ASSUME_NONNULL_END
