name: "Push source language to Transifex"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  push-translations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6.0.2 (previously v4)

      - name: l10n-push-source
        uses: transifex/cli-action@584fd205cbe598773b5a81ce711fa44842678189 # v2
        with:
          token: ${{ secrets.TX_TOKEN }}
          args: push -s
